ktor {
    deployment {
        port = 8080
        port = ${?KTOR_PORT}
        sslPort = ${?KTOR_SSL_PORT}
        watch = []
    }
    security {
        ssl {
            keyStore = ${?SSL_KEYSTORE}
            keyStorePassword = ${?SSL_KEYSTORE_PASSWORD}
            privateKeyPassword = ${?SSL_PRIVATE_KEY_PASSWORD}
        }
    }
    application {
        modules = [ com.virjar.tk.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:postgresql://127.0.0.1:5432/teamtalk"
    user = "teamtalk"
    password = ${?DATABASE_PASSWORD}
}

file {
    max-size-bytes = 157286400
    max-size-bytes = ${?FILE_MAX_SIZE_BYTES}
}
